# -*- coding: utf-8 -*-
"""CASINO

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zHV9yy13hmhKHM6jYG1V6oaJVuta6VOW
"""

from random import randint

bank = int(input('Введите Вашу сумму '))
tries = 3

def get_num():
  num = randint(1, 10)
  return num

def play(num, bank, tries):
  while tries > 0 and bank > 0:
    bet = input('Введите Вашу ставку ')
    if int(bet) > bank:
      print(f'В банке недостаточно средств, сделайте другую ставку. Всего в банке {bank}')
      continue
    user_num = input('Введите Ваше число ')
    if user_num.lower() == 'stop':
      return False
    elif int(user_num) == num:
      bank += int(bet) * 2
      print(f'Поздравляем, Вы угадали! Ваш выигрыш составил {int(bet) * 2}, всего в банке {bank}')
      return bank
    else:
      tries -= 1
    if tries == 0:
      bank -= int(bet)
      print(f'У Вас не осталось попыток. Игра закончена. Cумма в банке {bank}')
      return bank
    elif bank == 0:
      print('У Вас не осталось денег в банке. Игра закончена.')
      return False
    else:
      print(f'Вы не угадали, попробуйте ещё. Осталось попыток {tries}, сумма в банке {bank}')

if bank < 1000:
    print('Ваша сумма меньше 1000. Вход в казино закрыт')
else:
  while bank > 0:
    num = get_num()
    game = play(num, bank, tries)
    if game is False:
      break
    if game is not None:
      bank = int(game)