# -*- coding: utf-8 -*-
"""magic_ball.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cN3NIfeMoVxEVXxqebC1DZ4G27BZWphA
"""

from random import *
answers = ['Бесспорно', 'Предрешено', 'Никаких сомнений', 'Определённо да', 'Можешь быть уверен в этом', 'Мне кажется - да', 'Вероятнее всего', 'Хорошие перспективы', 'Знаки говорят - да', 'Да', 'Пока неясно, попробуй снова', 'Спроси позже', 'Лучше не рассказывать', 'Сейчас нельзя предсказать', 'Сконцентрируйся и спроси опять', 'Даже не думай', 'Мой ответ - нет', 'По моим данным - нет', 'Перспективы не очень хорошие', 'Весьма сомнительно']

print('Я - великий предсказатель судьбы!', 'С кем имею честь беседовать?', sep='\n')
name = input()
print('Приветствую тебя,', name)

def prediction():
  while True:
    print('Введи свой вопрос')
    question = input()
    print(choice(answers))
    break

prediction()

while True:
    print(f'Не желаешь задать ещё один вопрос, {name}?')
    y_n = input()
    if y_n.lower() == 'да':
      prediction()
    elif y_n.lower() == 'нет':
      print(f'Возвращайся, {name}, если возникнут вопросы!')
      break
    else:
      print('Я не понял ответ...')
      continue