# -*- coding: utf-8 -*-
"""safety_password_gen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A6H9jKiR15-NcLTXWBxwNXzXxQ2Noj_g
"""

from random import *

digits = '0123456789'
lowercase_letters = 'abcdefghijklmnopqrstuvwxyz'
uppercase_letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
punctuation = '!#$%&*+-=?@^_'
ambiguous_symbols = 'il1Lo0O'

chars = ''

print('Сколько паролей нужно?')
num = int(input())
print('Какая длина пароля?')
length = int(input())
print('Включать ли цифры 0123456789?; д = да, н = нет')
digit = input()
if digit == 'д':
  chars += digits
print('Включать ли прописные буквы ABCDEFGHIJKLMNOPQRSTUVWXYZ?; д = да, н = нет')
upper = input()
if upper == 'д':
  chars += uppercase_letters
print('Включать ли строчные буквы abcdefghijklmnopqrstuvwxyz?; д = да, н = нет')
lower = input()
if digit == 'д':
  lower += lowercase_letters
print('Включать ли символы !#$%&*+-=?@^_?; д = да, н = нет')
symbols = input()
if symbols == 'д':
  chars += punctuation
print('Исключать ли неоднозначные символы il1Lo0O?; д = да, н = нет')
similar_symbols = input()
if similar_symbols == 'д':
  for c in ambiguous_symbols:
    chars.replace(c, '')

def generate_password():
  password = sample(chars, length)
  print(''.join(password))

for _ in range(num):
  generate_password()